### ISSUE TITLE
ERR_CHALLENGE error ?

### ISSUE THREAD

**Issue by cleesmith** [mrgick/duck_chat#22]
```
pip install -U https://github.com/mrgick/duckduckgo-chat-ai/archive/master.zip
```

I always see: ERR_CHALLENGE 
... maybe from: duck_chat/duck_chat/api.py line 110: raise DuckChatException(err_message) but i don't see that error in the repo?

... or duck_chat, i see:
```
(duck_chat) cleesmith:~$ python -m duck_chat
Using claude-3-haiku-20240307
Type /help to display the help
>>> User input №1:
hello
>>> Response №1:
Error occurred: ERR_CHALLENGE
>>> User input №1:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/site-packages/duck_chat/cli.py", line 67, in run
    user_input = self.get_user_input()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/site-packages/duck_chat/cli.py", line 95, in get_user_input
    user_input = input()
                 ^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
```

... or using code example:

(duck_chat) cleesmith:~$ python -B cls.py
```
import asyncio
from duck_chat import DuckChat

async def main():
    async with DuckChat() as chat:
        print(await chat.ask_question("2+2?"))
        await asyncio.sleep(1)
        print(await chat.ask_question("6+6?"))

asyncio.run(main())
```
... i see:
```
Traceback (most recent call last):
  File "/Users/cleesmith/duck_chat/cls.py", line 10, in <module>
    asyncio.run(main())
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cleesmith/duck_chat/cls.py", line 6, in main
    print(await chat.ask_question("2+2?"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/site-packages/duck_chat/api.py", line 121, in ask_question
    message = await self.get_answer()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/duck_chat/lib/python3.12/site-packages/duck_chat/api.py", line 110, in get_answer
    raise DuckChatException(err_message)
duck_chat.exceptions.DuckChatException: ERR_CHALLENGE
```

**Comment by ReallyWeirdCat** [comment]
Same thing, apparently they resist automatic requests now

**Comment by HydraDragonAntivirus** [comment]
They probably fixed auto bot like requests.

**Comment by Legends-of-NGDB** [comment]
Any updates on this? Raw response: {"action":"error","status":418,"type":"ERR_CHALLENGE","overrideCode":"b46b","cd":{"cc":"duckchat","e":0,"er":null,"gk":0,"i":"3","iadb":1,"o":"pTHF7sUYy4pHMYhsbUeoeppLNdGPzHhRBRU0wj56nm6MSgYA5Hjumqwvz1FDXEnK%0A","p":"eefbca2019c84d259e4855e7d3b94a85-6cc56ef6960946b7b63c0250878e085e-cbde47337b1642ffb87a097633bd95f5-680872170de9477d9fde180d3b6eabd7-189bb05e30d14d9fa5954255fec981f5-5985cbeac86a47e0a8986197ca42e027-2cf1c84b886c4c339792bd8029da27bc-68b1202301f9410fb071405447975abb-720d685b76ac4756a2055ac8fa9bfb46","q":"","r":"use","s":"aichat","sc":1}}

**Comment by abdimk** [comment]
i created my own inspired by this package [**https://github.com/abdimk/Slang**](https://github.com/abdimk/Slang) the code is messy  but it works  


python3 -m venv myenv && source myenv/bin/activate && git clone https://github.com/abdimk/Slang && cd Slang && pip install dist/slang-1.0.0-py3-none-any.whl

**Comment by Sabdot33** [comment]
Nope! i don't think so, because they said they would allow third party clients to access the thing.
Also, requesting like this works:

```py
        async def create_custom_session():
            return aiohttp.ClientSession(
                headers={"User-Agent": "DuckChat Client",
                         "Connection": "keep-alive",
                         "Cookie": "yourcookies",
                         "x-vqd-4": "idk_what_this_is_for_its_probably_server_side_session_tracking"
                         },
                timeout=aiohttp.ClientTimeout(total=30)
            )

        custom_session = await create_custom_session()

        try:
            chat = DuckChat(session=custom_session)
            answer = await chat.ask_question(prompt)
            return answer
        finally:
            await custom_session.close()
```


but when i tried using a real browser-alike UA "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0" i would get the ERR_CHALLENGE again.
Also, i don't think that the cookies are necessary but i just included them.

**Comment by abdimk** [comment]
DuckDuckGo has been actively strengthening their anti-bot measures to prevent automated access to their chat API. but if anyone got a way to bypass this ??

**Comment by Sabdot33** [comment]
This time it seems more sophisticated, 
i looked into it and they have a new `x-vqd-hash-1` header in the request which contains a base64 encoded string of even more encoded stuff for both the client and server side but i have absolutely no clue what i could possibly do with these as of right now:

```json
{"server_hashes":["Iv/M1E37TbnES+NZoqLt+L1vuNzuLjd+Vju52XEBvUM=","Gjooz/xiQ0YGv9pEWawqIwQUElac/b/283X+96rOQkI="],
"client_hashes":["rUyo6nvBcJ6Pe7Hd/3jBkAyoH7QGOuvQpfRN9+GUTCI=","1vknKkk6AYqTxxs2+lGyWpcYgdmhOz/iP9uTCcYKi0o="],
"signals":{}}
```

Also alongside the ERR_CHALLENGE i encountered a new error message
`{"action":"error","status":429,"type":"ERR_SERVICE_UNAVAILABLE","r":"c6d8b851-d1a8-4514-9280-7d0695367d29"}`
but I think this is just for rate-limiting

**Comment by b1ek** [comment]
just run headless selenium to edit inputs and press buttons automatically at this point. lmao

**Comment by abdimk** [comment]
> just run headless selenium to edit inputs and press buttons automatically at this point. lmao
it won't be the same as automating  the requests and probably will be really slow 


or find a new endpoints duckduckgo is going crazy with the server-client encoding 

https://build.nvidia.com/explore/discover
